### ISSUE TITLE
Subnet names are not being updated

### ISSUE THREAD

**Issue by 3itSmartLife** [opentensor/developer-docs#109]
1. I want you to update the subnet names dynamically because some subnets were deregistered but their name remain in the docs.
2. Docs must keep pace with the changes and development of the entire Bittensor system. Some subnet names remain at their old ones.
Actually, the name of SN32 is BitAudit, not Roleplay.
3. https://docs.bittensor.com/subnet-pages/subnet-32#github
https://docs.bittensor.com/subnet-pages/subnet-5#github

**Comment by rajkaramchedu** [comment]
From Discord thread: 

"yeah there were a few subnets that are not up to date, 
sn5 is undetermined, 
sn24 is not bitads but automata - https://github.com/vn-automata/bt-automata, 
sn29 is fractal - https://github.com/fractal-net/fractal, 
sn32 is bitaudit - https://github.com/3itSmartLife/BitAudit

**Comment by rajkaramchedu** [comment]
Done.
