### ISSUE TITLE
Docs Suggestion: maybe you can have the docs translated into other language?

### ISSUE THREAD

**Issue by cynic-1** [opentensor/developer-docs#170]
Just like ethererm.org, I believe translation is a good way to let more people know about you.

**Comment by cynic-1** [comment]
I'm doing research on bittensor so I'm willing to translate the docs into Chinese by the way.

**Comment by rajkaramchedu** [comment]
Thanks, @cynic-1, it is on my list. Have you done any translations before? Any links?

**Comment by cynic-1** [comment]
> Thanks, @cynic-1, it is on my list. Have you done any translations before? Any links?

I'm not a professional translator, but I have done this kind of thing before.
you can check at:
https://github.com/zksync/credo/pull/10
