### ISSUE TITLE
Docs Bug in Bittensor Building Blocks Section

### ISSUE THREAD

**Issue by Cardoso-topdev** [opentensor/developer-docs#205]
1. Doc bug
2. Bittensor Building Blocks Section
    
![image](https://github.com/opentensor/developer-docs/assets/75736745/03a4af37-c565-4dc5-9b9a-ff1e7637d57f)

In Many-to-many bidirectional Notice, `the classical neural network shown on the right` should be changed to `the classical neural network shown on the left`
3. https://docs.bittensor.com/learn/bittensor-building-blocks

**Comment by rajkaramchedu** [comment]
Thanks, @Cardoso-topdev. Fixed.
