### ISSUE TITLE
Change "incentives" to "emissions" in the miner deregistration section

### ISSUE THREAD

**Issue by rajkaramchedu** [opentensor/developer-docs#228]
In this miner deregistration section https://docs.bittensor.com/subnets/register-validate-mine#miner-deregistration it is the emissions to the miner that are checked, not the incentives. Error alerted in this Discord thread: https://discord.com/channels/799672011265015819/799672011814862902/1240675838761111564

- Fix the text and the diagram

**Comment by crazydevlegend** [comment]
thanks for the quick fix @rajkaramchedu

**Comment by rajkaramchedu** [comment]
https://github.com/opentensor/developer-docs/pull/229 fixed
