### ISSUE TITLE
Docs Enhancement: Clarify the concept of "recycling"

### ISSUE THREAD

**Issue by yubrew** [opentensor/developer-docs#234]
This is an enhancement. The concept of recycling is not defined in the docs, but is a y/n question every time `tao` is spent.

Add a definition so it's searchable in the docs:

`It means to spend TAO.  However, the tokens you spend are not removed from the overall total of TAO that can be mined (if it were removed, that would be "burning").`

**Comment by rajkaramchedu** [comment]
https://github.com/opentensor/developer-docs/pull/342
