### ISSUE TITLE
用浏览器集成的钱包解除质押，总是不成功，为什么呀

### ISSUE THREAD

**Issue by logosjueyi** [opentensor/developer-docs#243]
账号
5HouDYojwnyXb44TLVd4kJcmwJZWc3xLvC7dtHv86sRkxZLW
谢谢

**Comment by rajkaramchedu** [comment]
@logosjueyi I think you asked "Unstaking with a browser-integrated wallet is always unsuccessful, why?" 
You will not get help from this Issues section of Docs to your question. Ask your question in the Optentensor Discord. Here is the link: https://discord.com/channels/799672011265015819/799672011814862902
