### ISSUE TITLE
Docs Bug or Enhancement or Suggestion (Edit this before submitting)

### ISSUE THREAD

**Issue by RathnamKV** [opentensor/developer-docs#368]
Where do we get testnet UID for subnet 37?

**Comment by rajkaramchedu** [comment]
You can run this command for registering with `netuid` value of 37 and adding the flag `--subtensor.network test` and that will register a UID for you and associate it with the hotkey you provide. 
![image](https://github.com/user-attachments/assets/3c5a8f77-131c-453c-9097-23b942966380)
