### ISSUE TITLE
Docs Enhancement - Add note about miner immunity period in commit reveal docs

### ISSUE THREAD

**Issue by yubrew** [opentensor/developer-docs#434]
Enhancement:

When changing miner immunity period in commit reveal period, 

`new miner_immunity_period = (new commit_reveal_weights_interval - old commit_reveal_weights_interval) + old miner_immunity_period`

this prevents a situation where miners can not get evaluated due to commit reveal interval being greater than immunity period for new miners.

**Comment by rajkaramchedu** [comment]
@MichaelTrestman If you want to take a shot at this...reassigned this to you.

**Comment by MichaelTrestman** [comment]
@yubrew 

Hello! I am either misunderstanding the feature or not finding the expected behavior.
I can get a subnet on my local chain to a state in which the immunity period is less than the commit reveal interval despite commit reveal being enabled. I did this by raising the commit reveal level to 1000 enabling commit reveal, then lowering the immunity period to 100.

Shouldn't this not be possible--shouldn't the resulting value after setting immunity period to 100 be 1100, i.e. 100 plus 1000 (the commit reveal weights interval)? Or is the extra 1000 grace period applied but not displayed as part of the configurable value?

Thank you!


```
 HYPERPARAMETER                     VALUE                  NORMALIZED
 ─────────────────────────────────────────────────────────────────────────
   rho                              10                     10
   kappa                            32767                  0.4999923705
   immunity_period                  100                    100
   min_allowed_weights              1                      1
   max_weight_limit                 65535                  1
   tempo                            360                    360
   min_difficulty                   18446744073709551615   1
   max_difficulty                   18446744073709551615   1
   weights_version                  0                      0
   weights_rate_limit               100                    100
   adjustment_interval              360                    360
   activity_cutoff                  5000                   5000
   registration_allowed             True                   True
   target_regs_per_interval         1                      1
   min_burn                         1                      τ0.000000001
   max_burn                         100000000000           τ100.000000000
   bonds_moving_avg                 900000                 4.878909776e-14
   max_regs_per_block               1                      1
   serving_rate_limit               50                     50
   max_validators                   64                     64
   adjustment_alpha                 17893341751498265066   0.97
   difficulty                       18446744073709551615   1
   commit_reveal_weights_interval   1000                   1000
   commit_reveal_weights_enabled    True                   True
   alpha_high                       58982                  0.9000076295
   alpha_low                        45875                  0.7000076295
   liquid_alpha_enabled             False                  False
 ─────────────────────────────────────────────────────────────────────────
```

**Comment by yubrew** [comment]
You can set everything as you suggested and the subnet will run fine from
your perspective. However new miners will not be able to get any emissions
since the immunity period will end before commit reveal, and also the new
miner can get kicked off easily. This was brought up in the last
NoveltySearch call by Isabella.
